### ISSUE TITLE
Blank Page nach Login.

### ISSUE THREAD

**Issue by vrkttr** [CrackTheNet/Core#1]
Registrierung funktioniert hervorragend. Nach dem Login jedoch erscheint nur noch eine blank page, ohne Fehlermeldungen.

**Comment by Bizarrus** [comment]
Könntest du vielleicht einmal sehen, ob ggf. die Errorlogs etwas aussagen? Vielleicht hast du ja nur das Error-Reporting aus.

Andernfalls kann es ggf sein, dass da noch ein paar Commits fehlen.

**Comment by Bizarrus** [comment]
Ich habe mal den letzten Stand von meinem Server committed :)

**Comment by vrkttr** [comment]
Danke für deine schnelle Antwort, jedoch hat das Updaten keinen Erfolg erbracht. Ebenso zeigt das ErrorLog von DF keinen einzigen Error an. 

/admin/ bleibt genauso leer.

Das Script wird auf einem DF Server in einer Subdomain und SSL-Zertifikat betrieben.

PHP 5.6 Stable: Hier erscheinen folgende Fehlermeldungen: Strict Standards: Non-static method CTN\Database::single() should not be called statically in /core/classes/options.class.php on line 10

PHP7 Stable: Dort werden die Fehlermeldungen nicht angezeigt.

**Comment by vrkttr** [comment]
Ich hab mal ein "**die("test");**" in _Core/themes/Neo/overview.php_ geschrieben und mich eingeloggt.
Es erfolgt keine Ausgabe, scheinbar wird die File nicht eingebunden.

Setze ich ein "**die("test");**" über 
```
$scope->getTemplate()->display('user/overview', [
		'logout_warning'	=> $logout_warning
	]);
```
in _Core/controller/user/overview.php_ erscheint "**test**".

Das einloggen funktioniert (der Cookie wird geschrieben) nur durch error_reporting(0);

**Comment by Bizarrus** [comment]
Ich schaue es mir gleich einmal an, ich bin derzeit noch mit einem anderen Projekt beschäftigt.

Die Entwicklung von `CrackTheNet` ist ohnehin vor Monaten stehen geblieben und das System ist noch nicht komplett fertig.

**Comment by vrkttr** [comment]
Hab das ganze nun mal auf einer XAMPP Umgebung installiert, dort tritt das selbe Problem auf.

Ich finde deinen Ansatz mit CrackTheNet super und würde mich sehr freuen wenn wir das wenigstens ans laufen bekommen würden.

**Comment by Bizarrus** [comment]
Was fixed with commit #f6c6484, #a90b038
